version: "3.7"

services:
  mongo:
    image: mongo:3.6.17-xenial
    ports:
      - "27017:27017"
    volumes:
      - /manual_da_obra/data/configdb:/data/configdb
      - /manual_da_obra/data/db:/data/db
    restart: always
    networks:
      - app-network

  backend:
    image: vpalmerini/manual_da_obra_backend
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env/prod/app.env
    environment:
      - NODE_ENV: production
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/log:/log
    depends_on:
      - mongo
    networks:
      - app-network
    command: node app.js

  frontend:
    image: manual_da_obra_frontend
    build:
      context: ./frontend
      args:
        API_URL: /api
    container_name: ui
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env/prod/ui.env
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: overlay
