version: "3.7"

services:
  mongo:
    image: mongo:3.6.17-xenial
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - /manual_da_obra/data/configdb:/data/configdb
      - /manual_da_obra/data/db:/data/db
    restart: always
    networks:
      - app-network

  backend:
    image: vpalmerini/manual_da_obra_backend
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      MONGO_INITDB_ROOT_PASSWORD: /run/secrets/db_password
      TOKEN_SECRET: /run/secrets/token_secret
      REFRESH_TOKEN_SECRET: /run/secrets/refresh_token_secret
      AWS_ACCESS_KEY_ID: /run/secrets/aws_access_key
      AWS_SECRET_ACCESS_KEY: /run/secrets/aws_secret_key
      INIT_PASSWORD: /run/secrets/init_password
      NODE_ENV: production
    secrets:
      - db_password
      - token_secret
      - refresh_token_secret
      - aws_access_key
      - aws_secret_key
      - init_password
    env_file:
      - .env/prod/app.env
    volumes:
      - /usr/src/app/node_modules
      - ./backend/log:/usr/src/app/log
    depends_on:
      - mongo
    networks:
      - app-network
    command: yarn start

  frontend:
    image: vpalmerini/manual_da_obra_frontend
    build:
      context: ./frontend
      args:
        API_URL: /api
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env/prod/ui.env
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: overlay

secrets:
  db_password:
   file: secrets/db_password.secret
  token_secret:
    file: secrets/token_secret.secret
  refresh_token_secret:
    file: secrets/refresh_token_secret.secret
  aws_access_key:
    file: secrets/aws_access_key.secret
  aws_secret_key:
    file: secrets/aws_secret_key.secret
  init_password:
    file: secrets/init_password.secret
